- name: Upgrade Ubuntu
  hosts: ubuntu_servers
  become: yes
  gather_facts: no  # To avoid fact gathering if not needed

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset: '!all'

    - name: Create backup directory on target servers
      ansible.builtin.file:
        path: /var/tmp/backups
        state: directory

    - name: Copy backup script to target servers
      ansible.builtin.copy:
        src: backup_script.sh
        dest: /usr/local/bin/backup_script.sh
        mode: '0755'

    - name: Execute backup script on target servers
      ansible.builtin.shell: /usr/local/bin/backup_script.sh
      args:
        chdir: /var/tmp

    - name: Create backup directory on control server
      delegate_to: localhost
      ansible.builtin.file:
        path: "/var/tmp/backups/{{ inventory_hostname }}"
        state: directory

    - name: Pull backups from target servers to control server
      ansible.builtin.synchronize:
        src: /var/tmp/backups/
        dest: "/var/tmp/backups/{{ inventory_hostname }}"
        mode: pull
      delegate_to: localhost

    - name: Check file system utilization
      ansible.builtin.command: df -h /
      register: disk_space

    - name: Fail if disk space utilization is over 85%
      ansible.builtin.fail:
        msg: "Disk space utilization is over 85%. Aborting upgrade."
      when: "(disk_space.stdout | regex_search('([0-9]+)% /') | int) > 85"

    - name: Check UFW status
      ansible.builtin.command: ufw status
      register: ufw_status

    - name: Stop UFW if it is active
      ansible.builtin.command: ufw disable
      when: "'Status: active' in ufw_status.stdout"

    - name: Check UFW status again
      ansible.builtin.command: ufw status
      register: ufw_status_after

    - name: Fail if UFW is still active
      ansible.builtin.fail:
        msg: "UFW is still active. Please disable it manually and retry."
      when: "'Status: active' in ufw_status_after.stdout"

    - name: Get current OS version before upgrade
      ansible.builtin.command: lsb_release -r
      register: os_version_before

    - name: Update all packages to the latest version
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install the update-manager-core package
      ansible.builtin.apt:
        name: update-manager-core
        state: present

    - name: Ensure all updates are applied
      ansible.builtin.command: apt-get dist-upgrade -y
      register: dist_upgrade_result

    - name: Reboot the server after applying updates
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after applying updates"
        pre_reboot_delay: 30
        post_reboot_delay: 60
      when: dist_upgrade_result.changed

    - name: Upgrade the distribution to Ubuntu
      ansible.builtin.command: do-release-upgrade -f DistUpgradeViewNonInteractive
      when: dist_upgrade_result.changed

    - name: Reboot the server after distribution upgrade
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for OS upgrade"
        pre_reboot_delay: 30
        post_reboot_delay: 60
      when: dist_upgrade_result.changed

    - name: Get OS version after upgrade
      ansible.builtin.command: lsb_release -r
      register: os_version_after

    - name: Fail if OS version has not changed
      ansible.builtin.fail:
        msg: "Upgrade failed. The OS version remains the same."
      when: os_version_before.stdout == os_version_after.stdout

    - name: Inform if OS version has changed, indicating a successful upgrade
      ansible.builtin.debug:
        msg: "Upgrade successful. OS version changed from {{ os_version_before.stdout }} to {{ os_version_after.stdout }}."
      when: os_version_before.stdout != os_version_after.stdout

